spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      pool-name: vboot-pool
      max-lifetime: 850000
      validation-timeout: 1000
      idle-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 25
      connection-test-query: select 1
      connection-timeout: 3000
      keepalive-time: 30000

  redis:
    redisson:
      config: |-
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 1000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          sslEnableEndpointIdentification: true
          sslProvider: "JDK"
          pingConnectionInterval: 30000
          keepAlive: true
          tcpNoDelay: true
          nameMapper: !<org.redisson.api.DefaultNameMapper> {}
          address: "redis://127.0.0.1:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 20
          connectionMinimumIdleSize: 5
          connectionPoolSize: 10
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        referenceEnabled: true
        transportMode: "NIO"
        lockWatchdogTimeout: 30000
        checkLockSyncedSlaves: true
        reliableTopicWatchdogTimeout: 600000
        keepPubSubOrder: true
        useScriptCache: false
        minCleanUpDelay: 5
        maxCleanUpDelay: 1800
        cleanUpKeysAmount: 100
        nettyHook: !<org.redisson.client.DefaultNettyHook> {}
        useThreadClassLoader: true
        addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}


# 自定义配置
vboot:
  swagger: true
  skip-urls:
    - /favicon.ico
    - /error
    - /v3/**
    - /**/*.html
    - /webjars/**
